name: Build Image

on: [push, pull_request, workflow_dispatch]

env:
  DOCKER_REGISTRY: registry.hub.docker.com    
  DOCKER_IMAGE: philosowaffle/swag-nginx-opentracing
  DOCKER_TARGET_PLATFORM: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx      
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${DOCKER_IMAGE}:latest
          platforms: ${DOCKER_TARGET_PLATFORM}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
