#!/usr/bin/with-contenv bash

echo "**** adding opentracing modules ****"

ls -l /

cp "/custom_modules/libopentracing.so" /usr/lib/nginx/modules/libopentracing.so.1
cp "/custom_modules/libopentracing.so" /usr/lib/nginx/modules/libopentracing.so
cp "/custom_modules/libzipkin.so" /usr/lib/nginx/modules/libzipkin.so.0
cp "/custom_modules/libzipkin.so" /usr/lib/nginx/modules/libzipkin.so
cp "/custom_modules/libzipkin_opentracing_plugin.so" /usr/lib/nginx/modules/libzipkin_opentracing.so.0
cp "/custom_modules/libzipkin_opentracing_plugin.so" /usr/lib/nginx/modules/libzipkin_opentracing.so
cp "/custom_modules/ngx_http_opentracing_module.so" /usr/lib/nginx/modules/ngx_http_opentracing_module.so

# mv /custom_modules/libopentracing.so /usr/lib/nginx/modules/libopentracing.so
# mv /custom_modules/libzipkin_opentracing_plugin.so /usr/lib/nginx/modules/libzipkin_opentracing_plugin.so
# mv /custom_modules/ngx_http_opentracing_module.so /usr/lib/nginx/modules/ngx_http_opentracing_module.so
